### ISSUE TITLE
crashes game

### ISSUE THREAD

**Issue by Hifilo** [Neorej/StellarisEmpireGenerator#16]
hey gave this a try.
generated and added to my existing empires.

1. gestalts & hiveminds load up broken
2. new games crash with all empires.

if it makes a difference I am using mods, but the empires aren't locked in game, so they are fine

**Comment by Neorej** [comment]
Hi, 
If you are willing to provide your `user_empire_designs_v3.4.txt` file here, I try to find any errors.

However it's incredibly likely this indeed caused by some mod (or corrupted game installation), as the designs file is only used to load the list of empires before starting a game. If there is any error in a generated empire, the game will simply gray it out, and never use the empire.
